ConversionRate Apr-May =
VAR StatusMap = DATATABLE(
    "StatusName", STRING,
    "StatusOrder", INTEGER,
    {
        {"L0: unqualifiziert", 0},
        {"L1: bewertet", 1},
        {"L2: qualifiziert", 2},
        {"L3: Konditionen akzeptiert", 3},
        {"L4: Flächen gesichert", 4},
        {"L5: Projekt gesichert", 5},
        {"M1: Aufstellungsbeschluss", 6},
        {"M2: Satzungsbeschluss", 7},
        {"lost", 99}
    }
)

VAR ConversionFunnels = DATATABLE(
    "FunnelName", STRING,
    "FromStatusOrder", INTEGER,
    "ToStatusOrder", INTEGER,
    {
        {"L0 → L1", 0, 1},
        {"L1 → L2", 1, 2},
        {"L2 → L3", 2, 3},
        {"L3 → L4", 3, 4},
        {"L4 → L5", 4, 5},
        {"L5 → M1", 5, 6}
    }
)

VAR EnrichedTable =
ADDCOLUMNS(
    'StatusHistorie_Projekte2025_Monat_Größe',
    "AprStatusOrder", LOOKUPVALUE(StatusMap[StatusOrder], StatusMap[StatusName], [Apr 2025]),
    "MayStatusOrder", LOOKUPVALUE(StatusMap[StatusOrder], StatusMap[StatusName], [May 2025])
)

VAR GeneratedConversions =
FILTER(
    CROSSJOIN(EnrichedTable, ConversionFunnels),
    (
        // Successful conversions
        ([AprStatusOrder] <= [FromStatusOrder] && [MayStatusOrder] >= [ToStatusOrder]) ||
        // Lost conversions
        ([AprStatusOrder] = [FromStatusOrder] && [MayStatusOrder] = 99)
    )
)

RETURN
SELECTCOLUMNS(
    GeneratedConversions,
    "ProjektID", [ProjektID],
    "ProjektName", [ProjektName],
    "Projektverantwortlicher", [Projektverantwortlicher],
    "Status_Apr2025", [Apr 2025],
    "Status_May2025", [May 2025],
    "Conversion", [FunnelName],
    "Category", IF([MayStatusOrder] = 99, "Lost aus " & [FunnelName], "Neu in " & [FunnelName])
)