ConversionRate Apr-May =
UNION(

    /* ---------- L0  →  L1 ---------- */
    SELECTCOLUMNS(
        FILTER(
            'StatusHistorie_Projekte2025_Monat_Größe',
            [Apr 2025] = "L0: unqualifiziert"  &&
            [May 2025] IN {
                "L1: bewertet","L2: qualifiziert","L3: Konditionen akzeptiert",
                "L4: Flächen gesichert","L5: Projekt gesichert",
                "M1: Aufstellungsbeschluss","M2: Satzungsbeschluss"
            }
        ),
        "ProjektID",               [ProjektID],
        "ProjektName",             [ProjektName],
        "Projektverantwortlicher", [Projektverantwortlicher],
        "Status_Apr2025",          [Apr 2025],
        "Status_May2025",          [May 2025],
        "Conversion",              "L0 → L1",
        "Category",                "Neu in L0 → L1"
    ),
    SELECTCOLUMNS(
        FILTER(
            'StatusHistorie_Projekte2025_Monat_Größe',
            [Apr 2025] = "L0: unqualifiziert" &&
            [May 2025] = "lost"
        ),
        "ProjektID",               [ProjektID],
        "ProjektName",             [ProjektName],
        "Projektverantwortlicher", [Projektverantwortlicher],
        "Status_Apr2025",          [Apr 2025],
        "Status_May2025",          [May 2025],
        "Conversion",              "L0 → L1",
        "Category",                "Lost aus L0 → L1"
    ),

    /* ---------- L1  →  L2 ---------- */
    SELECTCOLUMNS(
        FILTER(
            'StatusHistorie_Projekte2025_Monat_Größe',
            [Apr 2025] IN { "L0: unqualifiziert","L1: bewertet" }  &&
            [May 2025] IN {
                "L2: qualifiziert","L3: Konditionen akzeptiert","L4: Flächen gesichert",
                "L5: Projekt gesichert","M1: Aufstellungsbeschluss","M2: Satzungsbeschluss"
            }
        ),
        "ProjektID",               [ProjektID],
        "ProjektName",             [ProjektName],
        "Projektverantwortlicher", [Projektverantwortlicher],
        "Status_Apr2025",          [Apr 2025],
        "Status_May2025",          [May 2025],
        "Conversion",              "L1 → L2",
        "Category",                "Neu in L1 → L2"
    ),
    SELECTCOLUMNS(
        FILTER(
            'StatusHistorie_Projekte2025_Monat_Größe',
            [Apr 2025] = "L1: bewertet" &&
            [May 2025] = "lost"
        ),
        "ProjektID",               [ProjektID],
        "ProjektName",             [ProjektName],
        "Projektverantwortlicher", [Projektverantwortlicher],
        "Status_Apr2025",          [Apr 2025],
        "Status_May2025",          [May 2025],
        "Conversion",              "L1 → L2",
        "Category",                "Lost aus L1 → L2"
    ),

    /* ---------- L2  →  L3 ---------- */
    SELECTCOLUMNS(
        FILTER(
            'StatusHistorie_Projekte2025_Monat_Größe',
            [Apr 2025] IN { "L0: unqualifiziert","L1: bewertet","L2: qualifiziert" } &&
            [May 2025] IN {
                "L3: Konditionen akzeptiert","L4: Flächen gesichert","L5: Projekt gesichert",
                "M1: Aufstellungsbeschluss","M2: Satzungsbeschluss"
            }
        ),
        "ProjektID",               [ProjektID],
        "ProjektName",             [ProjektName],
        "Projektverantwortlicher", [Projektverantwortlicher],
        "Status_Apr2025",          [Apr 2025],
        "Status_May2025",          [May 2025],
        "Conversion",              "L2 → L3",
        "Category",                "Neu in L2 → L3"
    ),
    SELECTCOLUMNS(
        FILTER(
            'StatusHistorie_Projekte2025_Monat_Größe',
            [Apr 2025] = "L2: qualifiziert" &&
            [May 2025] = "lost"
        ),
        "ProjektID",               [ProjektID],
        "ProjektName",             [ProjektName],
        "Projektverantwortlicher", [Projektverantwortlicher],
        "Status_Apr2025",          [Apr 2025],
        "Status_May2025",          [May 2025],
        "Conversion",              "L2 → L3",
        "Category",                "Lost aus L2 → L3"
    ),

    /* ---------- L3  →  L4 ---------- */
    SELECTCOLUMNS(
        FILTER(
            'StatusHistorie_Projekte2025_Monat_Größe',
            [Apr 2025] IN {
                "L0: unqualifiziert","L1: bewertet","L2: qualifiziert","L3: Konditionen akzeptiert"
            } &&
            [May 2025] IN {
                "L4: Flächen gesichert","L5: Projekt gesichert",
                "M1: Aufstellungsbeschluss","M2: Satzungsbeschluss"
            }
        ),
        "ProjektID",               [ProjektID],
        "ProjektName",             [ProjektName],
        "Projektverantwortlicher", [Projektverantwortlicher],
        "Status_Apr2025",          [Apr 2025],
        "Status_May2025",          [May 2025],
        "Conversion",              "L3 → L4",
        "Category",                "Neu in L3 → L4"
    ),
    SELECTCOLUMNS(
        FILTER(
            'StatusHistorie_Projekte2025_Monat_Größe',
            [Apr 2025] = "L3: Konditionen akzeptiert" &&
            [May 2025] = "lost"
        ),
        "ProjektID",               [ProjektID],
        "ProjektName",             [ProjektName],
        "Projektverantwortlicher", [Projektverantwortlicher],
        "Status_Apr2025",          [Apr 2025],
        "Status_May2025",          [May 2025],
        "Conversion",              "L3 → L4",
        "Category",                "Lost aus L3 → L4"
    ),

    /* ---------- L4  →  L5 ---------- */
    SELECTCOLUMNS(
        FILTER(
            'StatusHistorie_Projekte2025_Monat_Größe',
            [Apr 2025] IN {
                "L0: unqualifiziert","L1: bewertet","L2: qualifiziert",
                "L3: Konditionen akzeptiert","L4: Flächen gesichert"
            } &&
            [May 2025] IN {
                "L5: Projekt gesichert","M1: Aufstellungsbeschluss","M2: Satzungsbeschluss"
            }
        ),
        "ProjektID",               [ProjektID],
        "ProjektName",             [ProjektName],
        "Projektverantwortlicher", [Projektverantwortlicher],
        "Status_Apr2025",          [Apr 2025],
        "Status_May2025",          [May 2025],
        "Conversion",              "L4 → L5",
        "Category",                "Neu in L4 → L5"
    ),
    SELECTCOLUMNS(
        FILTER(
            'StatusHistorie_Projekte2025_Monat_Größe',
            [Apr 2025] = "L4: Flächen gesichert" &&
            [May 2025] = "lost"
        ),
        "ProjektID",               [ProjektID],
        "ProjektName",             [ProjektName],
        "Projektverantwortlicher", [Projektverantwortlicher],
        "Status_Apr2025",          [Apr 2025],
        "Status_May2025",          [May 2025],
        "Conversion",              "L4 → L5",
        "Category",                "Lost aus L4 → L5"
    ),

    /* ---------- L5  →  M1 ---------- */
    SELECTCOLUMNS(
        FILTER(
            'StatusHistorie_Projekte2025_Monat_Größe',
            [Apr 2025] IN {
                "L0: unqualifiziert","L1: bewertet","L2: qualifiziert","L3: Konditionen akzeptiert",
                "L4: Flächen gesichert","L5: Projekt gesichert"
            } &&
            [May 2025] IN {
                "M1: Aufstellungsbeschluss","M2: Satzungsbeschluss"
            }
        ),
        "ProjektID",               [ProjektID],
        "ProjektName",             [ProjektName],
        "Projektverantwortlicher", [Projektverantwortlicher],
        "Status_Apr2025",          [Apr 2025],
        "Status_May2025",          [May 2025],
        "Conversion",              "L5 → M1",
        "Category",                "Neu in L5 → M1"
    ),
    SELECTCOLUMNS(
        FILTER(
            'StatusHistorie_Projekte2025_Monat_Größe',
            [Apr 2025] = "L5: Projekt gesichert" &&
            [May 2025] = "lost"
        ),
        "ProjektID",               [ProjektID],
        "ProjektName",             [ProjektName],
        "Projektverantwortlicher", [Projektverantwortlicher],
        "Status_Apr2025",          [Apr 2025],
        "Status_May2025",          [May 2025],
        "Conversion",              "L5 → M1",
        "Category",                "Lost aus L5 → M1"
    )

)  /* Ende UNION */
